# Docker environment for the SHOPWARE 6
version: '2'

services:
  server:
    build: ./.docker/nginx
    image: danneg/shpw6-nginx:1.17.8
    container_name: danneg_shpw6_nginx
    volumes:
      - ./.docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/conf/sites-enabled:/usr/local/bin/nginx/sites-enabled
      - ./.docker/nginx/conf/sites-available:/usr/local/bin/nginx/sites-available
      - ./.docker/nginx/logs:/var/log/nginx
    volumes_from:
      - code
    ports:
      - 80
      - 443
    depends_on:
      - php
      - database
    tty: true
    environment:
      SERVER_NAME: "dev-shpw6-comm.danneg.com"
    env_file:
      - ./.docker/nginx/.env
      - ./.env

  php:
    build: ./.docker/php
    image: danneg/shpw6-php:7.4.2
    container_name: danneg_comm__shpw6_php7.4.2
    volumes_from:
      - code
    volumes:
      - ./.docker/php/conf/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./.docker/php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./.docker/php/conf/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./.docker/php/logs:/var/log/php
    ports:
      - 9000
    links:
      - code
      - mailcatcher
    environment:
      PHP_IDE_CONFIG: "serverName=dev-shpw6-comm.danneg.com"

  database:
    build: ./.docker/mysql
    image: danneg/shpw6-mysql:8
    container_name: danneg_comm__shpw6_mysql8
    volumes_from:
    - dbdata
    depends_on:
    - dbdata
    volumes:
    - ./.docker/mysql/conf/:/etc/mysql/mysql.conf/
    - ./.docker/database/data:/var/lib/mysql
    ports:
    - 3306
    env_file:
    - ./.docker/mysql/.env

  shopware:
    build: ./.docker/cli
    image: danneg/shpw6-cli:7.4.2
    container_name: danneg_comm__shpw6_cli7.4.2
    links:
      - code
      - database
    volumes_from:
      - code
    volumes:
      - ./.docker/cli/conf/php.ini:/usr/local/etc/php/conf.d/php.ini
      - $HOME/.ssh/id_rsa:/root/.ssh/id_rsa
    environment:
      PROJECT_ROOT: "/var/www/shopware"
    env_file:
      - ./.docker/cli/.env
      - ./.docker/mysql/.env
      - ./.env

  mailcatcher:
    build: ./.docker/mailcatcher
    container_name: danneg_comm__shpw6_mailcatcher
    image: danneg/shpw6-mailcatcher:0.6.4
    ports:
    - 1080
    - 1025

  dbdata:
    image: tianon/true
    container_name: danneg_shpw6_comm__dbdata
    volumes:
    - /var/lib/mysql

  code:
    build: ./.docker/volume
    image: danneg/shpw6-volume
    container_name: danneg_comm__shpw6_volume
    volumes:
    - ./www:/var/www/shopware
    environment:
      SETUP_VOLUME: "/var/www/shopware"
