FROM mysql:5.7
MAINTAINER Dana Negrescu <dana.negrescu@boxalino.com>

##COPY bin/start /usr/local/bin/
#RUN chmod +x /usr/local/bin/start
#USER mysql

EXPOSE 3306

#ENTRYPOINT ["/usr/local/bin/start"]

