FROM mysql:5.7
MAINTAINER Dana Negrescu <dana.negrescu@boxalino.com>

#COPY ./conf/shpw.cnf /etc/mysql/conf.d
#COPY ./conf/my.cnf /etc/mysql
#
##COPY bin/start /usr/local/bin/
#RUN chmod 0444 /etc/mysql/conf.d/shpw.cnf
#
#USER mysql
EXPOSE 3306

#ENTRYPOINT ["/usr/local/bin/start"]

